<?php

use App\Http\Controllers\ColaboradorController;
use App\Http\Controllers\EmpresaController;
use App\Http\Controllers\EntradaLoteController;
use App\Http\Controllers\EstoqueController;
use App\Http\Controllers\FornecedorController;
use App\Http\Controllers\LocalController;
use App\Http\Controllers\MarcaController;
use App\Http\Controllers\PerfilController;
use App\Http\Controllers\SituacaoColaboradorController;
use App\Http\Controllers\TipoColaboradorController;
use App\Http\Controllers\TipoEstoqueController;
use App\Http\Controllers\TipoMaterialController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::inertia('/', 'welcome')->name('home');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::inertia('dashboard', 'geral/dashboard/dashboard')->name('dashboard');
    Route::get('users', [UserController::class, 'index'])->name('users.index');
    Route::post('users', [UserController::class, 'store'])->name('users.store');
    Route::patch('users/{user}', [UserController::class, 'update'])->name('users.update');
    Route::patch('users/{user}/status', [UserController::class, 'toggleStatus'])->name('users.toggle-status');
    Route::delete('users/{user}', [UserController::class, 'destroy'])->name('users.destroy');
    Route::get('empresas', [EmpresaController::class, 'index'])->name('empresas.index');
    Route::post('empresas', [EmpresaController::class, 'store'])->name('empresas.store');
    Route::patch('empresas/{empresa}', [EmpresaController::class, 'update'])->name('empresas.update');
    Route::patch('empresas/{empresa}/status', [EmpresaController::class, 'toggleStatus'])->name('empresas.toggle-status');
    Route::delete('empresas/{empresa}', [EmpresaController::class, 'destroy'])->name('empresas.destroy');
    Route::get('fornecedores', [FornecedorController::class, 'index'])->name('fornecedores.index');
    Route::post('fornecedores', [FornecedorController::class, 'store'])->name('fornecedores.store');
    Route::patch('fornecedores/{fornecedor}', [FornecedorController::class, 'update'])->name('fornecedores.update');
    Route::patch('fornecedores/{fornecedor}/status', [FornecedorController::class, 'toggleStatus'])->name('fornecedores.toggle-status');
    Route::delete('fornecedores/{fornecedor}', [FornecedorController::class, 'destroy'])->name('fornecedores.destroy');
    Route::get('perfis', [PerfilController::class, 'index'])->name('perfis.index');
    Route::post('perfis', [PerfilController::class, 'store'])->name('perfis.store');
    Route::patch('perfis/{perfil}', [PerfilController::class, 'update'])->name('perfis.update');
    Route::patch('perfis/{perfil}/status', [PerfilController::class, 'toggleStatus'])->name('perfis.toggle-status');
    Route::delete('perfis/{perfil}', [PerfilController::class, 'destroy'])->name('perfis.destroy');
    Route::get('locais', [LocalController::class, 'index'])->name('locais.index');
    Route::post('locais', [LocalController::class, 'store'])->name('locais.store');
    Route::patch('locais/{local}', [LocalController::class, 'update'])->name('locais.update');
    Route::patch('locais/{local}/status', [LocalController::class, 'toggleStatus'])->name('locais.toggle-status');
    Route::delete('locais/{local}', [LocalController::class, 'destroy'])->name('locais.destroy');
    Route::get('tipos-colaborador', [TipoColaboradorController::class, 'index'])->name('tipos-colaborador.index');
    Route::post('tipos-colaborador', [TipoColaboradorController::class, 'store'])->name('tipos-colaborador.store');
    Route::patch('tipos-colaborador/{tipoColaborador}', [TipoColaboradorController::class, 'update'])->name('tipos-colaborador.update');
    Route::patch('tipos-colaborador/{tipoColaborador}/status', [TipoColaboradorController::class, 'toggleStatus'])->name('tipos-colaborador.toggle-status');
    Route::delete('tipos-colaborador/{tipoColaborador}', [TipoColaboradorController::class, 'destroy'])->name('tipos-colaborador.destroy');
    Route::get('situacoes-colaborador', [SituacaoColaboradorController::class, 'index'])->name('situacoes-colaborador.index');
    Route::post('situacoes-colaborador', [SituacaoColaboradorController::class, 'store'])->name('situacoes-colaborador.store');
    Route::patch('situacoes-colaborador/{situacaoColaborador}', [SituacaoColaboradorController::class, 'update'])->name('situacoes-colaborador.update');
    Route::patch('situacoes-colaborador/{situacaoColaborador}/status', [SituacaoColaboradorController::class, 'toggleStatus'])->name('situacoes-colaborador.toggle-status');
    Route::delete('situacoes-colaborador/{situacaoColaborador}', [SituacaoColaboradorController::class, 'destroy'])->name('situacoes-colaborador.destroy');
    Route::get('colaboradores', [ColaboradorController::class, 'index'])->name('colaboradores.index');
    Route::post('colaboradores', [ColaboradorController::class, 'store'])->name('colaboradores.store');
    Route::patch('colaboradores/{colaborador}', [ColaboradorController::class, 'update'])->name('colaboradores.update');
    Route::delete('colaboradores/{colaborador}', [ColaboradorController::class, 'destroy'])->name('colaboradores.destroy');
    Route::get('config-estoque/tipos-materiais', [TipoMaterialController::class, 'index'])->name('tipos-materiais.index');
    Route::post('config-estoque/tipos-materiais', [TipoMaterialController::class, 'store'])->name('tipos-materiais.store');
    Route::patch('config-estoque/tipos-materiais/{tipoMaterial}', [TipoMaterialController::class, 'update'])->name('tipos-materiais.update');
    Route::patch('config-estoque/tipos-materiais/{tipoMaterial}/status', [TipoMaterialController::class, 'toggleStatus'])->name('tipos-materiais.toggle-status');
    Route::delete('config-estoque/tipos-materiais/{tipoMaterial}', [TipoMaterialController::class, 'destroy'])->name('tipos-materiais.destroy');
    Route::get('config-estoque/marcas', [MarcaController::class, 'index'])->name('marcas.index');
    Route::post('config-estoque/marcas', [MarcaController::class, 'store'])->name('marcas.store');
    Route::patch('config-estoque/marcas/{marca}', [MarcaController::class, 'update'])->name('marcas.update');
    Route::patch('config-estoque/marcas/{marca}/status', [MarcaController::class, 'toggleStatus'])->name('marcas.toggle-status');
    Route::delete('config-estoque/marcas/{marca}', [MarcaController::class, 'destroy'])->name('marcas.destroy');
    Route::get('config-estoque/tipos-estoque', [TipoEstoqueController::class, 'index'])->name('tipos-estoque.index');
    Route::post('config-estoque/tipos-estoque', [TipoEstoqueController::class, 'store'])->name('tipos-estoque.store');
    Route::patch('config-estoque/tipos-estoque/{tipoEstoque}', [TipoEstoqueController::class, 'update'])->name('tipos-estoque.update');
    Route::patch('config-estoque/tipos-estoque/{tipoEstoque}/status', [TipoEstoqueController::class, 'toggleStatus'])->name('tipos-estoque.toggle-status');
    Route::delete('config-estoque/tipos-estoque/{tipoEstoque}', [TipoEstoqueController::class, 'destroy'])->name('tipos-estoque.destroy');
    Route::get('operacoes-estoque/estoques', [EstoqueController::class, 'index'])->name('estoques.index');
    Route::post('operacoes-estoque/estoques', [EstoqueController::class, 'store'])->name('estoques.store');
    Route::patch('operacoes-estoque/estoques/{estoque}', [EstoqueController::class, 'update'])->name('estoques.update');
    Route::delete('operacoes-estoque/estoques/{estoque}', [EstoqueController::class, 'destroy'])->name('estoques.destroy');
    Route::get('operacoes-estoque/entradas-lote', [EntradaLoteController::class, 'index'])->name('entradas-lote.index');
    Route::get('operacoes-estoque/entradas-lote/nova', [EntradaLoteController::class, 'create'])->name('entradas-lote.create');
    Route::post('operacoes-estoque/entradas-lote', [EntradaLoteController::class, 'store'])->name('entradas-lote.store');
});

require __DIR__.'/settings.php';
